### ISSUE TITLE
"make install" fails to import service definition

### ISSUE THREAD

**Issue by michaelkoetter** [hadfl/kvmadm#76]
"make install" / "gmake install" fails with the following message:

```
if [ "xyes" = "xyes" ]; then svccfg import /opt/kvmadm-0.9.0-rc2/share/smf/system-kvm.xml; fi
svccfg: Unable to stat file /opt/kvmadm-0.9.0-rc2/share/smf/system-kvm.xml.  No such file or directory
```

`/opt/kvmadm-0.9.0-rc2` only contains `bin` and `lib` directories.
This is on a fresh OmniOS r151014 install, only added gnu-make package.

**Comment by michaelkoetter** [comment]
Also happens with 0.8.2 - no big deal, I just imported the file manually, but it's not pretty :)

**Comment by oetiker** [comment]
fixed in 5afa497

**Comment by michaelkoetter** [comment]
It still fails with current master:

```
gmake[3]: Entering directory `/root/kvmadm-20150501'
cd "/opt/kvmadm-20150501" && /usr/bin/perl -i -p -e 's{^#!.*perl.*}{#!/usr/bin/perl};' bin/kvmadm bin/system-kvm
if [ "xyes" = "xyes" ]; then svccfg import /opt/kvmadm-20150501/share/smf/system-kvm.xml; fi
svccfg: Unable to stat file /opt/kvmadm-20150501/share/smf/system-kvm.xml.  No such file or directory
```
I can see the change in Makefile.am, but Makefile.in still contains the old lines, as does the Makefile after configure.
Do I need to install automake & autoconf?

**Comment by oetiker** [comment]
I have not update Makefile.in ... run ./bootstrap to update them ... @hadfl will update them for the next rc

**Comment by michaelkoetter** [comment]
Thanks for the quick reply. I'll wait for the next rc then, don't want to install more than absolutely necessary in my global zone :)

**Comment by oetiker** [comment]
I have updated and pushed them ... @hadfl is currently on holiday ... :-)

**Comment by michaelkoetter** [comment]
Thank you, it works! Enjoy your holiday :)
